name: Python build

on:
  push:
    paths-ignore:
      - 'LICENSE.LGPL-3.0'
      - 'LICENSE.MIT'
      - 'README.md'
      - '.gitignore'

permissions:
  packages: write

env: 
  USERNAME: mojumi-alt
  VCPKG_EXE: C:/vcpkg/vcpkg
  FEED_URL: https://nuget.pkg.github.com/mojumi-alt/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/mojumi-alt/index.json,readwrite"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap vcpkg
        if: runner.os == 'Windows'
        shell: pwsh
        run: C:/vcpkg/bootstrap-vcpkg.bat
      - name: Add NuGet sources
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{ env.USERNAME }}" `
            -Password "${{ secrets.GITHUB_TOKEN }}"
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -Source "${{ env.FEED_URL }}"
      - name: Build wheels on ${{ matrix.os }}
        uses: pypa/cibuildwheel@v3.1.4