name: Python build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build wheels on ${{ matrix.os }}
        uses: pypa/cibuildwheel@v3.1.4